/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { Html, useGLTF, Billboard } from '@react-three/drei'
import HolographicMaterial from './shaders/HologramShader'
import { degToRad } from 'three/src/math/MathUtils'
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// Minimal hologram config for clean aesthetic
const minimalHologramProps = {
  hologramColor: "orangered",      // Soft cyan
  secondaryColor: "orangered",     // Teal accent
  accentColor: "red",        // Purple highlight
  hologramBrightness: 0.,
  hologramOpacity: 0.4,
  fresnelOpacity: 0.,
  fresnelAmount: 1.2,
  scanlineSize: 2.0,
  scanlineSpeed: 0.45,
  enableGrid: true,
  gridSize: 3.0,
  gridLineWidth: 2.0,
  enableHexPattern: true,
  enableDataStreams: true,
  enablePulseWaves: true,
  pulseSpeed: 1.0,
  wireframeIntensity: 0.,
  glitchIntensity: 0,
  chromaticStrength: 0.,
}

export function F1Model({ MainModelRef }) {
  const { nodes, materials } = useGLTF('model/partsTogether.glb')

  useEffect(() => {
    // Wait for HTML elements to be mounted in DOM
    const timer = setTimeout(() => {
      const htmlElements = document.querySelectorAll('[data-billboard-html]');
      
      if (htmlElements.length === 0) return;

      const ctx = gsap.context(() => {
        // Fade out all HTML billboards smoothly
        gsap.to(Array.from(htmlElements), {
          opacity: 0,
          scrollTrigger: {
            trigger: 'body',
            start: "8% center",
            end: "10% center",
            markers: false,
            scrub: true,
          },
        });
      });

      return () => ctx.revert();
    }, 200);

    return () => clearTimeout(timer);
  }, []);




  return (
    <group scale={0.014} rotation={[degToRad(90), degToRad(90), degToRad(0)]} dispose={null}>
      <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_1.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_2.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_3.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_4.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_5.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_6.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_7.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_8.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_9.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_10.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
      </group>

      <Billboard position={[0, 120, 220]}>
        <Html transform>
          <div data-billboard-html className='h-[150vw] w-[150vw] border-red border-[5vw] text-white text-2xl font-bold flex items-center justify-center' style={{ opacity: 1 }}>
            <p className='text-[30vw] translate-x-[90%] translate-y-[-80%] leading-none font-mono text-white'>AERODYNAMICS</p>
          </div>
        </Html>
      </Billboard>
      <Billboard position={[0, 0, -220]}>
        <Html transform>
          <div data-billboard-html className='h-[150vw] w-[150vw] border-red border-[5vw] text-white text-2xl font-bold flex items-center justify-center' style={{ opacity: 1 }}>
            <p className='text-[30vw] translate-x-[-150%] translate-y-[-80%] whitespace-nowrap w-full font-mono leading-none  text-white'>FRONT WING</p>
          </div>
        </Html>
      </Billboard>
      <Billboard position={[-100, 30, 20]}>
        <Html occlude transform>
          <div data-billboard-html className='h-[150vw] w-[150vw] border-red border-[5vw] text-white text-2xl font-bold flex items-center justify-center' style={{ opacity: 1 }}>
            <p className='text-[30vw] translate-x-[120%] translate-y-[-80%] whitespace-nowrap w-full font-mono leading-none  text-white'>MONOCOQUE</p>
          </div>
        </Html>
      </Billboard>
    </group>
  )
}
